spring.application.name=MindSpark-Quiz
spring.datasource.username=root
server.port=8080
spring.datasource.password=yadavarvind7
spring.datasource.url=jdbc:mysql://localhost:3306/MindSparkquiz?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.validation.fail-fast=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arvyadav936987@gmail.com
spring.mail.password=eiaefvanmbarkzek
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

